import type { CharacterRecord } from '$lib/types/global';

const charName: CharacterRecord = {
  uid: 10000038,
  url: 'UI_AvatarIcon_Albedo',
  id: 'albedo',
  name: 'albedo',
  fullName: 'Albedo',
  region: 'mondstat',
  rating: 5,
  weapon: 'sword',
  vision: 'geo',
  specialized: 'geo',
  c3: 'skill',
  c5: 'burst',
  burstCost: 40,
  talentNames: {
    normal: 'Favonius Bladework - Weiss',
    skill: 'Abiogenesis: Solar Isotoma',
    burst: 'Rite of Progeniture: Tectonic Tide'
  },
  normal: [
    {
      name: '1 - Hit DMG',
      tag: 'N1',
      damageBonus: 'normal',
      damage: [
        [
          {
            scaling: 'atk',
            param: 'param1'
          }
        ]
      ]
    },
    {
      name: '2 - Hit DMG',
      tag: 'N2',
      damageBonus: 'normal',
      damage: [
        [
          {
            scaling: 'atk',
            param: 'param2'
          }
        ]
      ]
    },
    {
      name: '3 - Hit DMG',
      tag: 'N3',
      damageBonus: 'normal',
      damage: [
        [
          {
            scaling: 'atk',
            param: 'param3'
          }
        ]
      ]
    },
    {
      name: '4 - Hit DMG',
      tag: 'N4',
      damageBonus: 'normal',
      damage: [
        [
          {
            scaling: 'atk',
            param: 'param4'
          }
        ]
      ]
    },
    {
      name: '5 - Hit DMG',
      tag: 'N5',
      damageBonus: 'normal',
      damage: [
        [
          {
            scaling: 'atk',
            param: 'param5'
          }
        ]
      ]
    }
  ],
  charged: [
    {
      name: 'Charged Attack',
      tag: 'CA',
      damageBonus: 'charged',
      damage: [
        [
          {
            scaling: 'atk',
            param: 'param6'
          }
        ],
        [
          {
            scaling: 'atk',
            param: 'param7'
          }
        ]
      ]
    }
  ],
  plunge: [
    {
      name: 'Plunge DMG',
      tag: 'PD',
      damageBonus: 'plunge',
      damage: [
        [
          {
            scaling: 'atk',
            param: 'param9'
          }
        ]
      ]
    },
    {
      name: 'Low Plunge',
      tag: 'PL',
      damageBonus: 'plunge',
      damage: [
        [
          {
            scaling: 'atk',
            param: 'param10'
          }
        ]
      ]
    },
    {
      name: 'High Plunge',
      tag: 'PH',
      damageBonus: 'plunge',
      damage: [
        [
          {
            scaling: 'atk',
            param: 'param11'
          }
        ]
      ]
    }
  ],
  skill: [
    {
      name: 'Skill DMG',
      tag: 'E',
      damageBonus: 'skill',
      url: 'Skill_S_Albedo_01',
      damage: [
        [
          {
            scaling: 'atk',
            param: 'param1'
          }
        ]
      ]
    },
    {
      name: 'Transient Blossom DMG',
      tag: 'EC',
      damageBonus: 'skill',
      url: 'Skill_S_Albedo_01',
      hasOwnBonusDMG: 'transientBlossoms',
      damage: [
        [
          {
            scaling: 'def',
            param: 'param2'
          }
        ]
      ]
    }
  ],
  burst: [
    {
      name: 'Burst DMG',
      tag: 'Q1',
      damageBonus: 'burst',
      url: 'Skill_E_Albedo_01',
      hasOwnBonusFlatDMG: 'phanerozoic',
      damage: [
        [
          {
            scaling: 'atk',
            param: 'param1'
          }
        ]
      ]
    },
    {
      name: 'Fatal Blossom DMG - Total',
      tag: 'Q2',
      damageBonus: 'burst',
      url: 'Skill_E_Albedo_01',
      hasOwnBonusFlatDMG: 'phanerozoic',
      damage: [
        [
          {
            scaling: 'atk',
            param: 'param2'
          }
        ],
        [
          {
            scaling: 'atk',
            param: 'param2'
          }
        ],
        [
          {
            scaling: 'atk',
            param: 'param2'
          }
        ],
        [
          {
            scaling: 'atk',
            param: 'param2'
          }
        ],
        [
          {
            scaling: 'atk',
            param: 'param2'
          }
        ],
        [
          {
            scaling: 'atk',
            param: 'param2'
          }
        ],
        [
          {
            scaling: 'atk',
            param: 'param2'
          }
        ]
      ]
    },
    {
      name: 'Fatal Blossom DMG ',
      damageBonus: 'burst',
      url: 'Skill_E_Albedo_01',
      hasOwnBonusFlatDMG: 'phanerozoic',
      damage: [
        [
          {
            scaling: 'atk',
            param: 'param2'
          }
        ]
      ]
    }
  ],
  actions: [
    {
      name: 'Calcite Might',
      url: 'UI_Talent_S_Albedo_05',
      description:
        'Transient Blossoms generated by **Abiogenesis: Solar Isotoma** deal 25% more DMG to opponents whose HP is below 50%.',
      level: 2,
      target: 'self',
      actionType: 'toggle',
      values: [
        {
          scaling: 'transientBlossoms',
          coef: 0.25
        }
      ]
    },
    {
      name: 'Homuncular Nature',
      url: 'UI_Talent_S_Albedo_06',
      description:
        'Using **Rite of Progeniture: Tectonic Tide** increases the Elemental Mastery of nearby party members by 125 for 10s.',
      level: 8,
      target: 'nearby',
      actionType: 'toggle',
      values: [
        {
          scaling: 'em',
          coef: 125
        }
      ]
    },
    {
      name: 'Opening of Phanerozoic',
      url: 'UI_Talent_S_Albedo_02',
      description:
        "Transient Blossoms generated by **Abiogenesis: Solar Isotoma** grant Albedo Fatal Reckoning for 30s:\n·Unleashing **Rite of Progeniture: Tectonic Tide** consumes all stacks of Fatal Reckoning. Each stack of Fatal Reckoning consumed increases the DMG dealt by Fatal Blossoms and Rite of Progeniture: Tectonic Tide's burst DMG by 30% of Albedo's DEF.\n·This effect stacks up to 4 times.",
      constellation: 2,
      target: 'self',
      actionType: 'stack',
      sourceStats: ['def'],
      values: [
        {
          scaling: 'phanerozoic',
          coef: [0.3, 0.3, 0.3, 0.3],
          source: ['def', 0]
        }
      ]
    },
    {
      name: 'Descent of Divinity',
      url: 'UI_Talent_S_Albedo_03',
      description:
        'Active party members within the Solar Isotoma field have their Plunging Attack DMG increased by 30%.',
      constellation: 4,
      target: 'active',
      actionType: 'passive',
      values: [
        {
          scaling: 'plunge',
          coef: 0.3
        }
      ]
    },
    {
      name: 'Dust of Purification',
      url: 'UI_Talent_S_Albedo_04',
      description:
        'Active party members within the Solar Isotoma field who are protected by a shield created by Crystallize have their DMG increased by 17%.',
      constellation: 6,
      target: 'active',
      actionType: 'toggle',
      values: [
        {
          scaling: 'dmgIncrease',
          coef: 0.17
        }
      ]
    }
  ]
};

export default charName;
