import type { CharacterRecord } from '$lib/types/global';

const charName: CharacterRecord = {
  uid: 10000074,
  id: 'layla',
  name: 'layla',
  fullName: 'Layla',
  rating: 4,
  weapon: 'sword',
  region: 'sumeru',
  vision: 'cryo',
  specialized: 'hp%',
  c3: 'skill',
  c5: 'burst',
  burstCost: 40,
  talentNames: {
    normal: 'Sword of the Radiant Path',
    skill: 'Nights of Formal Focus',
    burst: 'Dream of the Star-Stream Shaker'
  },
  normal: [
    {
      name: '1 - Hit DMG',
      tag: 'N1',
      damageBonus: 'normal',
      damage: [
        [
          {
            scaling: 'atk',
            param: 'param1'
          }
        ]
      ]
    },
    {
      name: '2 - Hit DMG',
      tag: 'N2',
      damageBonus: 'normal',
      damage: [
        [
          {
            scaling: 'atk',
            param: 'param2'
          }
        ]
      ]
    },
    {
      name: '3 - Hit DMG',
      tag: 'N3',
      damageBonus: 'normal',
      damage: [
        [
          {
            scaling: 'atk',
            param: 'param3'
          }
        ]
      ]
    }
  ],
  charged: [
    {
      name: 'Charged Attack',
      tag: 'CA',
      damageBonus: 'charged',
      damage: [
        [
          {
            scaling: 'atk',
            param: 'param4'
          }
        ],
        [
          {
            scaling: 'atk',
            param: 'param5'
          }
        ]
      ]
    }
  ],
  plunge: [
    {
      name: 'Plunge DMG',
      tag: 'PD',
      damageBonus: 'plunge',
      damage: [
        [
          {
            scaling: 'atk',
            param: 'param7'
          }
        ]
      ]
    },
    {
      name: 'Low Plunge',
      tag: 'PL',
      damageBonus: 'plunge',
      damage: [
        [
          {
            scaling: 'atk',
            param: 'param8'
          }
        ]
      ]
    },
    {
      name: 'High Plunge',
      tag: 'PH',
      damageBonus: 'plunge',
      damage: [
        [
          {
            scaling: 'atk',
            param: 'param9'
          }
        ]
      ]
    }
  ],
  skill: [
    {
      name: 'Skill DMG',
      tag: 'E1',
      damageBonus: 'skill',
      url: 'Skill_S_Layla_01',
      damage: [
        [
          {
            scaling: 'atk',
            param: 'param1'
          }
        ]
      ]
    },
    {
      name: 'Shooting Star DMG',
      tag: 'E2',
      hasOwnBonusFlatDMG: 'shootingStars',
      hasOwnBonusDMG: 'radiantSoulfire',
      damageBonus: 'skill',
      url: 'Skill_S_Layla_01',
      damage: [
        [
          {
            scaling: 'atk',
            param: 'param2'
          }
        ]
      ]
    },
    {
      name: 'Base Shield DMG Absorption',
      damageBonus: 'skill',
      isShield: true,
      damage: [
        [
          {
            scaling: 'hp',
            param: 'param3'
          },
          {
            scaling: 'flatValue',
            param: 'param4'
          }
        ]
      ]
    }
  ],
  burst: [
    {
      name: 'Starlight Slug DMG',
      tag: 'Q',
      hasOwnBonusDMG: 'radiantSoulfire',
      damageBonus: 'burst',
      url: 'Skill_E_Layla_01',
      damage: [
        [
          {
            scaling: 'hp',
            param: 'param1'
          }
        ]
      ]
    }
  ],
  actions: [
    {
      name: 'Like Nascent Light',
      url: 'UI_Talent_S_Layla_05',
      description:
        'While the **Curtain of Slumber** is active, the Deep Sleep effect will activate each time the Curtain gains 1 Night Star:\n·The Shield Strength of a character under the effect of the Curtain of Slumber increases by 6%.\n·This effect can have a maximum of 4 stacks and persists until the Curtain of Slumber disappears.',
      level: 2,
      target: 'active',
      actionType: 'toggle',
      values: [
        {
          scaling: 'shieldStrength',
          coef: [0.06, 0.06, 0.06, 0.06]
        }
      ]
    },
    {
      name: 'Sweet Slumber Undisturbed',
      url: 'UI_Talent_S_Layla_06',
      description:
        "The DMG dealt by the Shooting Stars fired by **Nights of Formal Focus** is increased by 1.5% of Layla's Max HP.",
      level: 8,
      target: 'self',
      actionType: 'passive',
      values: [
        {
          scaling: 'shootingStars',
          coef: 0.015,
          source: ['hp', 0]
        }
      ]
    },
    {
      name: 'Fortress of Fantasy',
      url: 'UI_Talent_S_Layla_01',
      description:
        'The Shield Absorption of the Curtain of Slumber generated by **Nights of Formal Focus** is increased by 20%.',
      constellation: 1,
      target: 'self',
      actionType: 'passive',
      values: [
        {
          scaling: 'shieldStrength',
          coef: 0.2
        }
      ]
    },
    {
      name: 'Starry Illumination',
      url: 'UI_Talent_S_Layla_03',
      description:
        "When **Nights of Formal Focus** starts to fire off Shooting Stars, it will grant all nearby party members the Dawn Star effect, causing their Normal and Charged Attack DMG to increase based on 5% of Layla's Max HP.\nDawn Star can last up to 3s and will be removed 0.05s after dealing Normal or Charged Attack DMG.",
      constellation: 4,
      target: 'party',
      actionType: 'toggle',
      values: [
        {
          scaling: 'chargedFlatDMG',
          coef: 0.05,
          source: ['hp', 0]
        },
        {
          scaling: 'normalFlatDMG',
          coef: 0.05,
          source: ['hp', 0]
        }
      ]
    },
    {
      name: 'Radiant Soulfire',
      url: 'UI_Talent_S_Layla_04',
      description:
        'Shooting Stars from **Nights of Formal Focus** deal 40% increased DMG, and Starlight Slugs from **Dream of the Star-Stream Shaker** deal 40% increased DMG.\nAdditionally, the interval between the creation of Night Stars via Nights of Formal Focus is decreased by 20%.',
      constellation: 6,
      target: 'self',
      actionType: 'passive',
      values: [
        {
          scaling: 'radiantSoulfire',
          coef: 0.4
        }
      ]
    }
  ],
  offField: []
};

export default charName;
