export const StatsMap = new Map([
  ['atk', 'ATK'],
  ['def', 'DEF'],
  ['hp', 'HP'],
  ['atk%', 'ATK%'],
  ['def%', 'DEF%'],
  ['hp%', 'HP%'],
  ['em', 'Elemental Mastery'],
  ['critrate', 'CRIT Rate'],
  ['critdmg', 'CRIT DMG'],
  ['energy', 'Energy Recharge'],
  ['healing', 'Healing Bonus'],
  ['healingIncoming', 'Incoming Healing Bonus'],
  ['anemo', 'Anemo DMG Bonus'],
  ['cryo', 'Cryo DMG Bonus'],
  ['dendro', 'Dendro DMG Bonus'],
  ['electro', 'Electro DMG Bonus'],
  ['geo', 'Geo DMG Bonus'],
  ['hydro', 'Hydro DMG Bonus'],
  ['pyro', 'Pyro DMG Bonus'],
  ['physical', 'Physical DMG Bonus'],
  ['anemoRes', 'Anemo Res'],
  ['cryoRes', 'Cryo Res'],
  ['dendroRes', 'Dendro Res'],
  ['electroRes', 'Electro Res'],
  ['geoRes', 'Geo Res'],
  ['hydroRes', 'Hydro Res'],
  ['pyroRes', 'Pyro Res'],
  ['physicalRes', 'Physical Res'],
  ['dmgIncrease', 'DMG Increase'],
  ['dmgIncreaseElemental', 'Elemental DMG Increase'],
  ['normal', 'Normal DMG Bonus'],
  ['charged', 'Charged DMG Bonus'],
  ['plunge', 'Plunge DMG Bonus'],
  ['skill', 'Skill DMG Bonus'],
  ['burst', 'Burst DMG Bonus'],
  ['normalATKSpd', 'Normal ATK Speed'],
  ['chargedATKSpd', 'Charged ATK Speed'],
  ['moveSpd', 'Movement Speed'],
  ['normalSpecialMultiplier', 'Normal ATK Modifier'],
  ['chargedSpecialMultiplier', 'Charged ATK Modifier'],
  ['plungeSpecialMultiplier', 'Plunge ATK Modifier'],
  ['skillSpecialMultiplier', 'Skill DMG Modifier'],
  ['burstSpecialMultiplier', 'Burst DMG Modifier'],
  ['normalFlatDMG', 'Normal ATK Flat DMG'],
  ['chargedFlatDMG', 'Charged ATK Flat DMG'],
  ['plungeFlatDMG', 'Plunge ATK Flat DMG'],
  ['skillFlatDMG', 'Skill Flat DMG'],
  ['burstFlatDMG', 'Burst Flat DMG'],
  ['normalCritRate', 'Normal ATK CRIT Rate'],
  ['chargedCritRate', 'Charged ATK CRIT Rate'],
  ['plungeCritRate', 'Plunge ATK CRIT Rate'],
  ['skillCritRate', 'Skill CRIT Rate'],
  ['burstCritRate', 'Burst CRIT Rate'],
  ['normalCritDMG', 'Normal ATK CRIT DMG'],
  ['chargedCritDMG', 'Charged ATK CRIT DMG'],
  ['plungeCritDMG', 'Plunge ATK CRIT DMG'],
  ['skillCritDMG', 'Skill CRIT DMG'],
  ['burstCritDMG', 'Burst CRIT DMG'],
  ['normalDefIgnore', 'Normal ATK DEF Ignore'],
  ['chargedDefIgnore', 'Charged ATK DEF Ignore'],
  ['plungeDefIgnore', 'Plunge ATK DEF Ignore'],
  ['skillDefIgnore', 'Skill DEF Ignore'],
  ['burstDefIgnore', 'Burst DEF Ignore'],
  ['defReduce', 'DEF Reduction'],
  ['dmgReduction', 'DMG Reduction'],
  ['partyBurstCost', 'Party Total Burst Cost'],
  ['partyMaxEM', 'Party Max EM'],
  ['partyAvgBurstCost', 'Party Average Burst Cost'],
  ['aggravate', 'Aggravate DMG Bonus'],
  ['spread', 'Spread DMG Bonus'],
  ['melt', 'Melt DMG Bonus'],
  ['vaporize', 'Vaporize DMG Bonus'],
  ['burning', 'Burning DMG Bonus'],
  ['superconduct', 'Superconduct DMG Bonus'],
  ['swirl', 'Swirl DMG Bonus'],
  ['hydroSwirl', 'Hydro Swirl DMG Bonus'],
  ['pyroSwirl', 'Pyro Swirl DMG Bonus'],
  ['cryoSwirl', 'Cryo Swirl DMG Bonus'],
  ['electroSwirl', 'Electro Swirl DMG Bonus'],
  ['electrocharged', 'Electrocharged DMG Bonus'],
  ['shattered', 'Shattered DMG Bonus'],
  ['overloaded', 'Overloaded DMG Bonus'],
  ['bloom', 'Bloom DMG Bonus'],
  ['burgeon', 'Burgeon DMG Bonus'],
  ['hyperbloom', 'Hyperbloom DMG Bonus'],
  ['crystallize', 'Crystallize Bonus'],
  ['shieldStrength', 'Shield Strength'],
  ['flatValue', 'Flat Value']
]);

export function getStatLabel(key: string): string {
  return StatsMap.get(key) || key.charAt(0).toUpperCase() + key.slice(1);
}
